# Generated by Django 3.2.18 on 2024-07-13 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_classified', '0010_remove_payment_balance'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_classified.profile')),
            ],
        ),
    ]
